### ISSUE TITLE
Fragment number is 4 bit (currently 2 bit)

### ISSUE THREAD

**Issue by techge** [radiotap/python-radiotap#1]
Hi,
may I am wrong, but as I read the ieee802.11 standard, the fragment number should be 4 bit of the sequence control field, as far as I understand [this line](
https://github.com/radiotap/python-radiotap/blob/master/radiotap/radiotap.py#L426) it is currently only 2 bit. Or am I wrong?

Thx for the library anyway.

Kind regards
Alex

**Comment by bcopeland** [comment]
Oops, you are right.  Pushed a fix, thanks!
