### ISSUE TITLE
Python 3 compatibility in tests

### ISSUE THREAD

**Issue by kristahi** [radiotap/python-radiotap#7]
Hi again,

following up on #5, I realized I had forgotten to commit changes to tests/parse.py to make it run properly under Python 3.

I've cleaned up the changes and made sure they work correctly in Python 2.7 as well as 3.
I grabbed (with attribution) the `iterbytes` function from the [six module](https://pypi.org/project/six/), which is MIT licensed so should be compatible licensing-wise.

Submitting PR shortly.

**Comment by jmberg** [comment]
I guess I should've checked, but given how trivial it looked ...

thanks!

**Comment by kristahi** [comment]
Yeah, I should have checked on a clean checkout before submitting the first PR, sorry for the noise.

The changes to `parse.py` were much more significant, the library code ran just fine after changing the imports :)
